version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: myserver
      POSTGRES_PASSWORD: "-_nEOpKBawnmqSyJSRkaqPHZEbncUVaq"
    volumes:
      - myserver_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "t73o5J099mkEPTZNNNv7WNN2Gz2B_cAF"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  myserver_data:
